package com.example.multimedia.juniorseoul.DataHouse;

import com.example.multimedia.juniorseoul.Classess.ArtImgModel;
import com.example.multimedia.juniorseoul.Classess.KidsCafeModel;
import com.example.multimedia.juniorseoul.Classess.MemorialImgModel;
import com.example.multimedia.juniorseoul.Classess.MuseumImgModel;
import com.example.multimedia.juniorseoul.Classess.NTImgModel;
import com.example.multimedia.juniorseoul.Classess.TImgModel;
import com.example.multimedia.juniorseoul.R;

import java.util.ArrayList;
import java.util.List;

public class StaticData {

    public static List<ArtImgModel> artImgList = new ArrayList<ArtImgModel>() {
        {
            add(new ArtImgModel(R.drawable.art_001));
            add(new ArtImgModel(R.drawable.art_002));
            add(new ArtImgModel(R.drawable.art_003));
            add(new ArtImgModel(R.drawable.art_004));
            add(new ArtImgModel(R.drawable.art_005));
            add(new ArtImgModel(R.drawable.art_006));
            add(new ArtImgModel(R.drawable.art_007));
            add(new ArtImgModel(R.drawable.art_008));
            add(new ArtImgModel(R.drawable.art_009));
            add(new ArtImgModel(R.drawable.art_010));
            add(new ArtImgModel(R.drawable.art_011));
            add(new ArtImgModel(R.drawable.art_012));
            add(new ArtImgModel(R.drawable.art_013));
            add(new ArtImgModel(R.drawable.art_014));
            add(new ArtImgModel(R.drawable.art_015));
            add(new ArtImgModel(R.drawable.art_016));
            add(new ArtImgModel(R.drawable.art_017));
            add(new ArtImgModel(R.drawable.art_018));
            add(new ArtImgModel(R.drawable.art_019));
            add(new ArtImgModel(R.drawable.art_020));
            add(new ArtImgModel(R.drawable.art_021));
            add(new ArtImgModel(R.drawable.art_022));
            add(new ArtImgModel(R.drawable.art_023));
            add(new ArtImgModel(R.drawable.art_024));
            add(new ArtImgModel(R.drawable.art_025));
            add(new ArtImgModel(R.drawable.art_026));
            add(new ArtImgModel(R.drawable.art_027));
            add(new ArtImgModel(R.drawable.art_028));
            add(new ArtImgModel(R.drawable.art_029));
            add(new ArtImgModel(R.drawable.art_030));
            add(new ArtImgModel(R.drawable.art_031));
            add(new ArtImgModel(R.drawable.art_032));
            add(new ArtImgModel(R.drawable.art_033));
            add(new ArtImgModel(R.drawable.art_034));
            add(new ArtImgModel(R.drawable.art_035));
            add(new ArtImgModel(R.drawable.art_036));
        }
    };

    public static List<MemorialImgModel> memorialImgList = new ArrayList<MemorialImgModel>() {
        {
            add(new MemorialImgModel(R.drawable.memorial_001));
            add(new MemorialImgModel(R.drawable.memorial_002));
            add(new MemorialImgModel(R.drawable.memorial_003));
            add(new MemorialImgModel(R.drawable.memorial_004));
            add(new MemorialImgModel(R.drawable.memorial_005));
            add(new MemorialImgModel(R.drawable.memorial_006));
            add(new MemorialImgModel(R.drawable.memorial_007));
            add(new MemorialImgModel(R.drawable.memorial_008));
            add(new MemorialImgModel(R.drawable.memorial_009));
        }
    };

    public static List<MuseumImgModel> museumImgList = new ArrayList<MuseumImgModel>() {
        {
            add(new MuseumImgModel(R.drawable.museum_001));
            add(new MuseumImgModel(R.drawable.museum_002));
            add(new MuseumImgModel(R.drawable.museum_003));
            add(new MuseumImgModel(R.drawable.museum_004));
            add(new MuseumImgModel(R.drawable.museum_005));
            add(new MuseumImgModel(R.drawable.museum_006));
            add(new MuseumImgModel(R.drawable.museum_007));
            add(new MuseumImgModel(R.drawable.museum_008));
            add(new MuseumImgModel(R.drawable.museum_009));
            add(new MuseumImgModel(R.drawable.museum_010));
            add(new MuseumImgModel(R.drawable.museum_011));
            add(new MuseumImgModel(R.drawable.museum_012));
            add(new MuseumImgModel(R.drawable.museum_013));
            add(new MuseumImgModel(R.drawable.museum_014));
            add(new MuseumImgModel(R.drawable.museum_015));
            add(new MuseumImgModel(R.drawable.museum_016));
            add(new MuseumImgModel(R.drawable.museum_017));
            add(new MuseumImgModel(R.drawable.museum_018));
            add(new MuseumImgModel(R.drawable.museum_019));
            add(new MuseumImgModel(R.drawable.museum_020));
            add(new MuseumImgModel(R.drawable.museum_021));
            add(new MuseumImgModel(R.drawable.museum_022));
            add(new MuseumImgModel(R.drawable.museum_023));
            add(new MuseumImgModel(R.drawable.museum_024));
            add(new MuseumImgModel(R.drawable.museum_025));
            add(new MuseumImgModel(R.drawable.museum_026));
            add(new MuseumImgModel(R.drawable.museum_027));
            add(new MuseumImgModel(R.drawable.museum_028));
            add(new MuseumImgModel(R.drawable.museum_029));
            add(new MuseumImgModel(R.drawable.museum_030));
            add(new MuseumImgModel(R.drawable.museum_031));
            add(new MuseumImgModel(R.drawable.museum_032));
            add(new MuseumImgModel(R.drawable.museum_033));
            add(new MuseumImgModel(R.drawable.museum_034));
            add(new MuseumImgModel(R.drawable.museum_035));
            add(new MuseumImgModel(R.drawable.museum_036));
            add(new MuseumImgModel(R.drawable.museum_037));
            add(new MuseumImgModel(R.drawable.museum_038));
            add(new MuseumImgModel(R.drawable.museum_039));
            add(new MuseumImgModel(R.drawable.museum_040));
            add(new MuseumImgModel(R.drawable.museum_041));
            add(new MuseumImgModel(R.drawable.museum_042));
            add(new MuseumImgModel(R.drawable.museum_043));
            add(new MuseumImgModel(R.drawable.museum_044));
            add(new MuseumImgModel(R.drawable.museum_045));
            add(new MuseumImgModel(R.drawable.museum_046));
            add(new MuseumImgModel(R.drawable.museum_047));
            add(new MuseumImgModel(R.drawable.museum_048));
            add(new MuseumImgModel(R.drawable.museum_049));
            add(new MuseumImgModel(R.drawable.museum_050));
            add(new MuseumImgModel(R.drawable.museum_051));
            add(new MuseumImgModel(R.drawable.museum_052));
            add(new MuseumImgModel(R.drawable.museum_053));
            add(new MuseumImgModel(R.drawable.museum_054));
            add(new MuseumImgModel(R.drawable.museum_055));
            add(new MuseumImgModel(R.drawable.museum_056));
            add(new MuseumImgModel(R.drawable.museum_057));
            add(new MuseumImgModel(R.drawable.museum_058));
            add(new MuseumImgModel(R.drawable.museum_059));
            add(new MuseumImgModel(R.drawable.museum_060));
            add(new MuseumImgModel(R.drawable.museum_061));
            add(new MuseumImgModel(R.drawable.museum_062));
            add(new MuseumImgModel(R.drawable.museum_063));
            add(new MuseumImgModel(R.drawable.museum_064));
            add(new MuseumImgModel(R.drawable.museum_065));
            add(new MuseumImgModel(R.drawable.museum_066));
            add(new MuseumImgModel(R.drawable.museum_067));
            add(new MuseumImgModel(R.drawable.museum_068));
            add(new MuseumImgModel(R.drawable.museum_069));
            add(new MuseumImgModel(R.drawable.museum_070));
            add(new MuseumImgModel(R.drawable.museum_071));
            add(new MuseumImgModel(R.drawable.museum_072));
            add(new MuseumImgModel(R.drawable.museum_073));
            add(new MuseumImgModel(R.drawable.museum_074));
        }
    };

    public static List<NTImgModel> ntJoongu = new ArrayList<NTImgModel>() {
        {
            add(new NTImgModel(R.drawable.trsr_nt_b_001));
            add(new NTImgModel(R.drawable.trsr_nt_b_083));
            add(new NTImgModel(R.drawable.trsr_nt_b_096));
            add(new NTImgModel(R.drawable.trsr_nt_b_097));
            add(new NTImgModel(R.drawable.trsr_nt_b_100));
        }
    };

    public static List<NTImgModel> ntKangnam = new ArrayList<NTImgModel>() {
        {
            add(new NTImgModel(R.drawable.trsr_nt_x_149));
        }
    };

    public static List<NTImgModel> ntYongsan = new ArrayList<NTImgModel>() {
        {
            add(new NTImgModel(R.drawable.trsr_nt_d_003));
            add(new NTImgModel(R.drawable.trsr_nt_d_004));
            add(new NTImgModel(R.drawable.trsr_nt_d_005));
            add(new NTImgModel(R.drawable.trsr_nt_d_014));
            add(new NTImgModel(R.drawable.trsr_nt_d_015));
            add(new NTImgModel(R.drawable.trsr_nt_d_016));
            add(new NTImgModel(R.drawable.trsr_nt_d_017));
            add(new NTImgModel(R.drawable.trsr_nt_d_018));
            add(new NTImgModel(R.drawable.trsr_nt_d_019));
            add(new NTImgModel(R.drawable.trsr_nt_d_020));
            add(new NTImgModel(R.drawable.trsr_nt_d_021));
            add(new NTImgModel(R.drawable.trsr_nt_d_022));
            add(new NTImgModel(R.drawable.trsr_nt_d_023));
            add(new NTImgModel(R.drawable.trsr_nt_d_024));
            add(new NTImgModel(R.drawable.trsr_nt_d_025));
            add(new NTImgModel(R.drawable.trsr_nt_d_026));
            add(new NTImgModel(R.drawable.trsr_nt_d_027));
            add(new NTImgModel(R.drawable.trsr_nt_d_028));
            add(new NTImgModel(R.drawable.trsr_nt_d_029));
            add(new NTImgModel(R.drawable.trsr_nt_d_030));
            add(new NTImgModel(R.drawable.trsr_nt_d_031));
            add(new NTImgModel(R.drawable.trsr_nt_d_032));
            add(new NTImgModel(R.drawable.trsr_nt_d_033));
            add(new NTImgModel(R.drawable.trsr_nt_d_034));
            add(new NTImgModel(R.drawable.trsr_nt_d_035));
            add(new NTImgModel(R.drawable.trsr_nt_d_037));
            add(new NTImgModel(R.drawable.trsr_nt_d_038));
            add(new NTImgModel(R.drawable.trsr_nt_d_039));
            add(new NTImgModel(R.drawable.trsr_nt_d_040));
            add(new NTImgModel(R.drawable.trsr_nt_d_041));
            add(new NTImgModel(R.drawable.trsr_nt_d_042));
            add(new NTImgModel(R.drawable.trsr_nt_d_043));
            add(new NTImgModel(R.drawable.trsr_nt_d_044));
            add(new NTImgModel(R.drawable.trsr_nt_d_046));
            add(new NTImgModel(R.drawable.trsr_nt_d_047));
            add(new NTImgModel(R.drawable.trsr_nt_d_048));
            add(new NTImgModel(R.drawable.trsr_nt_d_049));
            add(new NTImgModel(R.drawable.trsr_nt_d_050));
            add(new NTImgModel(R.drawable.trsr_nt_d_051));
            add(new NTImgModel(R.drawable.trsr_nt_d_053));
            add(new NTImgModel(R.drawable.trsr_nt_d_054));
            add(new NTImgModel(R.drawable.trsr_nt_d_055));
            add(new NTImgModel(R.drawable.trsr_nt_d_056));
            add(new NTImgModel(R.drawable.trsr_nt_d_057));
            add(new NTImgModel(R.drawable.trsr_nt_d_058));
            add(new NTImgModel(R.drawable.trsr_nt_d_061));
            add(new NTImgModel(R.drawable.trsr_nt_d_062));
            add(new NTImgModel(R.drawable.trsr_nt_d_072));
            add(new NTImgModel(R.drawable.trsr_nt_d_073));
            add(new NTImgModel(R.drawable.trsr_nt_d_074));
            add(new NTImgModel(R.drawable.trsr_nt_d_075));
            add(new NTImgModel(R.drawable.trsr_nt_d_076));
            add(new NTImgModel(R.drawable.trsr_nt_d_077));
            add(new NTImgModel(R.drawable.trsr_nt_d_078));
            add(new NTImgModel(R.drawable.trsr_nt_d_079));
            add(new NTImgModel(R.drawable.trsr_nt_d_081));
            add(new NTImgModel(R.drawable.trsr_nt_d_082));
            add(new NTImgModel(R.drawable.trsr_nt_d_085));
            add(new NTImgModel(R.drawable.trsr_nt_d_087));
            add(new NTImgModel(R.drawable.trsr_nt_d_088));
            add(new NTImgModel(R.drawable.trsr_nt_d_089));
            add(new NTImgModel(R.drawable.trsr_nt_d_090));
            add(new NTImgModel(R.drawable.trsr_nt_d_091));
            add(new NTImgModel(R.drawable.trsr_nt_d_092));
            add(new NTImgModel(R.drawable.trsr_nt_d_093));
            add(new NTImgModel(R.drawable.trsr_nt_d_094));
            add(new NTImgModel(R.drawable.trsr_nt_d_098));
            add(new NTImgModel(R.drawable.trsr_nt_d_101));
            add(new NTImgModel(R.drawable.trsr_nt_d_102));
            add(new NTImgModel(R.drawable.trsr_nt_d_103));
            add(new NTImgModel(R.drawable.trsr_nt_d_104));
            add(new NTImgModel(R.drawable.trsr_nt_d_105));
            add(new NTImgModel(R.drawable.trsr_nt_d_106));
            add(new NTImgModel(R.drawable.trsr_nt_d_107));
            add(new NTImgModel(R.drawable.trsr_nt_d_108));
            add(new NTImgModel(R.drawable.trsr_nt_d_118));
            add(new NTImgModel(R.drawable.trsr_nt_d_119));
            add(new NTImgModel(R.drawable.trsr_nt_d_122));
            add(new NTImgModel(R.drawable.trsr_nt_d_123));
            add(new NTImgModel(R.drawable.trsr_nt_d_124));
            add(new NTImgModel(R.drawable.trsr_nt_d_125));
            add(new NTImgModel(R.drawable.trsr_nt_d_126));
            add(new NTImgModel(R.drawable.trsr_nt_d_130));
            add(new NTImgModel(R.drawable.trsr_nt_d_131));
            add(new NTImgModel(R.drawable.trsr_nt_d_133));
            add(new NTImgModel(R.drawable.trsr_nt_d_134));
            add(new NTImgModel(R.drawable.trsr_nt_d_135));
            add(new NTImgModel(R.drawable.trsr_nt_d_136));
            add(new NTImgModel(R.drawable.trsr_nt_d_137));
            add(new NTImgModel(R.drawable.trsr_nt_d_144));
            add(new NTImgModel(R.drawable.trsr_nt_d_145));
            add(new NTImgModel(R.drawable.trsr_nt_d_146));
            add(new NTImgModel(R.drawable.trsr_nt_d_147));
            add(new NTImgModel(R.drawable.trsr_nt_d_150));
            add(new NTImgModel(R.drawable.trsr_nt_d_155));

        }
    };

    public static List<NTImgModel> ntSungbuk = new ArrayList<NTImgModel>() {
        {
            add(new NTImgModel(R.drawable.trsr_nt_h_006));
            add(new NTImgModel(R.drawable.trsr_nt_h_007));
            add(new NTImgModel(R.drawable.trsr_nt_h_008));
            add(new NTImgModel(R.drawable.trsr_nt_h_009));
            add(new NTImgModel(R.drawable.trsr_nt_h_010));
            add(new NTImgModel(R.drawable.trsr_nt_h_011));
            add(new NTImgModel(R.drawable.trsr_nt_h_012));
            add(new NTImgModel(R.drawable.trsr_nt_h_013));
            add(new NTImgModel(R.drawable.trsr_nt_h_052));
            add(new NTImgModel(R.drawable.trsr_nt_h_065));
            add(new NTImgModel(R.drawable.trsr_nt_h_084));
            add(new NTImgModel(R.drawable.trsr_nt_h_116));
            add(new NTImgModel(R.drawable.trsr_nt_h_127));
            add(new NTImgModel(R.drawable.trsr_nt_h_143));
            add(new NTImgModel(R.drawable.trsr_nt_h_151));
            add(new NTImgModel(R.drawable.trsr_nt_h_152));

        }
    };

    public static List<NTImgModel> ntSeocho = new ArrayList<NTImgModel>() {
        {
            add(new NTImgModel(R.drawable.trsr_nt_j_064));
            add(new NTImgModel(R.drawable.trsr_nt_j_132));
            add(new NTImgModel(R.drawable.trsr_nt_j_157));

        }
    };

    public static List<NTImgModel> ntSeodaemun = new ArrayList<NTImgModel>() {
        {
            add(new NTImgModel(R.drawable.trsr_nt_k_036));
            add(new NTImgModel(R.drawable.trsr_nt_k_095));
            add(new NTImgModel(R.drawable.trsr_nt_k_128));
            add(new NTImgModel(R.drawable.trsr_nt_k_129));
            add(new NTImgModel(R.drawable.trsr_nt_k_154));
        }
    };

    public static List<NTImgModel> ntDongjak = new ArrayList<NTImgModel>() {
        {
            add(new NTImgModel(R.drawable.trsr_nt_m_059));
            add(new NTImgModel(R.drawable.trsr_nt_m_117));
        }
    };

    public static List<NTImgModel> ntKwangjin = new ArrayList<NTImgModel>() {
        {
            add(new NTImgModel(R.drawable.trsr_nt_s_060));
        }
    };

    public static List<NTImgModel> ntKwanak = new ArrayList<NTImgModel>() {
        {
            add(new NTImgModel(R.drawable.trsr_nt_t_063));
            add(new NTImgModel(R.drawable.trsr_nt_t_066));
            add(new NTImgModel(R.drawable.trsr_nt_t_067));
            add(new NTImgModel(R.drawable.trsr_nt_t_069));
            add(new NTImgModel(R.drawable.trsr_nt_t_070));
            add(new NTImgModel(R.drawable.trsr_nt_t_071));
            add(new NTImgModel(R.drawable.trsr_nt_t_086));
            add(new NTImgModel(R.drawable.trsr_nt_t_099));
            add(new NTImgModel(R.drawable.trsr_nt_t_109));
            add(new NTImgModel(R.drawable.trsr_nt_t_139));
            add(new NTImgModel(R.drawable.trsr_nt_t_140));
            add(new NTImgModel(R.drawable.trsr_nt_t_141));
            add(new NTImgModel(R.drawable.trsr_nt_t_142));
            add(new NTImgModel(R.drawable.trsr_nt_t_148));
            add(new NTImgModel(R.drawable.trsr_nt_t_153));
        }
    };

    public static List<NTImgModel> ntJongro = new ArrayList<NTImgModel>() {
        {
            add(new NTImgModel(R.drawable.trsr_nt_y_002));
            add(new NTImgModel(R.drawable.trsr_nt_y_045));
            add(new NTImgModel(R.drawable.trsr_nt_y_068));
            add(new NTImgModel(R.drawable.trsr_nt_y_110));
            add(new NTImgModel(R.drawable.trsr_nt_y_111));
            add(new NTImgModel(R.drawable.trsr_nt_y_112));
            add(new NTImgModel(R.drawable.trsr_nt_y_113));
            add(new NTImgModel(R.drawable.trsr_nt_y_114));
            add(new NTImgModel(R.drawable.trsr_nt_y_115));
            add(new NTImgModel(R.drawable.trsr_nt_y_120));
            add(new NTImgModel(R.drawable.trsr_nt_y_121));
            add(new NTImgModel(R.drawable.trsr_nt_y_138));
            add(new NTImgModel(R.drawable.trsr_nt_y_156));
        }
    };
    public static List<TImgModel> tJunggu = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_b_090));
        add(new TImgModel(R.drawable.trsr_t_b_172));
        add(new TImgModel(R.drawable.trsr_t_b_173));
        add(new TImgModel(R.drawable.trsr_t_b_174));
        add(new TImgModel(R.drawable.trsr_t_b_177));
        add(new TImgModel(R.drawable.trsr_t_b_178));
        add(new TImgModel(R.drawable.trsr_t_b_179));
        add(new TImgModel(R.drawable.trsr_t_b_180));
        add(new TImgModel(R.drawable.trsr_t_b_181));
        add(new TImgModel(R.drawable.trsr_t_b_183));
        add(new TImgModel(R.drawable.trsr_t_b_201));
        add(new TImgModel(R.drawable.trsr_t_b_206));
        add(new TImgModel(R.drawable.trsr_t_b_215));
        add(new TImgModel(R.drawable.trsr_t_b_216));
        add(new TImgModel(R.drawable.trsr_t_b_245));
        add(new TImgModel(R.drawable.trsr_t_b_246));
        add(new TImgModel(R.drawable.trsr_t_b_292));
        add(new TImgModel(R.drawable.trsr_t_b_294));
        add(new TImgModel(R.drawable.trsr_t_b_295));
        add(new TImgModel(R.drawable.trsr_t_b_316));
        add(new TImgModel(R.drawable.trsr_t_b_332));
        add(new TImgModel(R.drawable.trsr_t_b_504));
        add(new TImgModel(R.drawable.trsr_t_b_524));
        add(new TImgModel(R.drawable.trsr_t_b_655));
    }};

    public static List<TImgModel> tEunpyeong = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_c_138));
        add(new TImgModel(R.drawable.trsr_t_c_525));
        add(new TImgModel(R.drawable.trsr_t_c_566));
    }};
    public static List<TImgModel> tYongsan = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_d_002));
        add(new TImgModel(R.drawable.trsr_t_d_007));
        add(new TImgModel(R.drawable.trsr_t_d_009));
        add(new TImgModel(R.drawable.trsr_t_d_014));
        add(new TImgModel(R.drawable.trsr_t_d_016));
        add(new TImgModel(R.drawable.trsr_t_d_018));
        add(new TImgModel(R.drawable.trsr_t_d_019));
        add(new TImgModel(R.drawable.trsr_t_d_021));
        add(new TImgModel(R.drawable.trsr_t_d_028));
        add(new TImgModel(R.drawable.trsr_t_d_029));
        add(new TImgModel(R.drawable.trsr_t_d_030));
        add(new TImgModel(R.drawable.trsr_t_d_031));
        add(new TImgModel(R.drawable.trsr_t_d_032));
        add(new TImgModel(R.drawable.trsr_t_d_033));
        add(new TImgModel(R.drawable.trsr_t_d_034));
        add(new TImgModel(R.drawable.trsr_t_d_035));
        add(new TImgModel(R.drawable.trsr_t_d_036));
        add(new TImgModel(R.drawable.trsr_t_d_037));
        add(new TImgModel(R.drawable.trsr_t_d_038));
        add(new TImgModel(R.drawable.trsr_t_d_039));
        add(new TImgModel(R.drawable.trsr_t_d_040));
        add(new TImgModel(R.drawable.trsr_t_d_045));
        add(new TImgModel(R.drawable.trsr_t_d_046));
        add(new TImgModel(R.drawable.trsr_t_d_047));
        add(new TImgModel(R.drawable.trsr_t_d_048));
        add(new TImgModel(R.drawable.trsr_t_d_049));
        add(new TImgModel(R.drawable.trsr_t_d_050));
        add(new TImgModel(R.drawable.trsr_t_d_051));
        add(new TImgModel(R.drawable.trsr_t_d_059));
        add(new TImgModel(R.drawable.trsr_t_d_065));
        add(new TImgModel(R.drawable.trsr_t_d_066));
        add(new TImgModel(R.drawable.trsr_t_d_067));
        add(new TImgModel(R.drawable.trsr_t_d_068));
        add(new TImgModel(R.drawable.trsr_t_d_069));
        add(new TImgModel(R.drawable.trsr_t_d_071));
        add(new TImgModel(R.drawable.trsr_t_d_072));
        add(new TImgModel(R.drawable.trsr_t_d_075));
        add(new TImgModel(R.drawable.trsr_t_d_076));
        add(new TImgModel(R.drawable.trsr_t_d_077));
        add(new TImgModel(R.drawable.trsr_t_d_081));
        add(new TImgModel(R.drawable.trsr_t_d_082));
        add(new TImgModel(R.drawable.trsr_t_d_083));
        add(new TImgModel(R.drawable.trsr_t_d_084));
        add(new TImgModel(R.drawable.trsr_t_d_085));
        add(new TImgModel(R.drawable.trsr_t_d_086));
        add(new TImgModel(R.drawable.trsr_t_d_088));
        add(new TImgModel(R.drawable.trsr_t_d_091));
        add(new TImgModel(R.drawable.trsr_t_d_094));
        add(new TImgModel(R.drawable.trsr_t_d_108));
        add(new TImgModel(R.drawable.trsr_t_d_111));
        add(new TImgModel(R.drawable.trsr_t_d_114));
        add(new TImgModel(R.drawable.trsr_t_d_115));
        add(new TImgModel(R.drawable.trsr_t_d_116));
        add(new TImgModel(R.drawable.trsr_t_d_117));
        add(new TImgModel(R.drawable.trsr_t_d_119));
        add(new TImgModel(R.drawable.trsr_t_d_122));
        add(new TImgModel(R.drawable.trsr_t_d_123));
        add(new TImgModel(R.drawable.trsr_t_d_124));
        add(new TImgModel(R.drawable.trsr_t_d_125));
        add(new TImgModel(R.drawable.trsr_t_d_126));
        add(new TImgModel(R.drawable.trsr_t_d_132));
        add(new TImgModel(R.drawable.trsr_t_d_135));
        add(new TImgModel(R.drawable.trsr_t_d_147));
        add(new TImgModel(R.drawable.trsr_t_d_148));
        add(new TImgModel(R.drawable.trsr_t_d_149));
        add(new TImgModel(R.drawable.trsr_t_d_150));
        add(new TImgModel(R.drawable.trsr_t_d_151));
        add(new TImgModel(R.drawable.trsr_t_d_153));
        add(new TImgModel(R.drawable.trsr_t_d_154));
        add(new TImgModel(R.drawable.trsr_t_d_156));
        add(new TImgModel(R.drawable.trsr_t_d_157));
        add(new TImgModel(R.drawable.trsr_t_d_159));
        add(new TImgModel(R.drawable.trsr_t_d_162));
        add(new TImgModel(R.drawable.trsr_t_d_184));
        add(new TImgModel(R.drawable.trsr_t_d_186));
        add(new TImgModel(R.drawable.trsr_t_d_189));
        add(new TImgModel(R.drawable.trsr_t_d_198));
        add(new TImgModel(R.drawable.trsr_t_d_209));
        add(new TImgModel(R.drawable.trsr_t_d_217));
        add(new TImgModel(R.drawable.trsr_t_d_218));
        add(new TImgModel(R.drawable.trsr_t_d_219));
        add(new TImgModel(R.drawable.trsr_t_d_220));
        add(new TImgModel(R.drawable.trsr_t_d_221));
        add(new TImgModel(R.drawable.trsr_t_d_222));
        add(new TImgModel(R.drawable.trsr_t_d_223));
        add(new TImgModel(R.drawable.trsr_t_d_224));
        add(new TImgModel(R.drawable.trsr_t_d_225));
        add(new TImgModel(R.drawable.trsr_t_d_226));
        add(new TImgModel(R.drawable.trsr_t_d_227));
        add(new TImgModel(R.drawable.trsr_t_d_228));
        add(new TImgModel(R.drawable.trsr_t_d_229));
        add(new TImgModel(R.drawable.trsr_t_d_230));
        add(new TImgModel(R.drawable.trsr_t_d_264));
        add(new TImgModel(R.drawable.trsr_t_d_276));
        add(new TImgModel(R.drawable.trsr_t_d_277));
        add(new TImgModel(R.drawable.trsr_t_d_278));
        add(new TImgModel(R.drawable.trsr_t_d_279));
        add(new TImgModel(R.drawable.trsr_t_d_283));
        add(new TImgModel(R.drawable.trsr_t_d_284));
        add(new TImgModel(R.drawable.trsr_t_d_293));
        add(new TImgModel(R.drawable.trsr_t_d_296));
        add(new TImgModel(R.drawable.trsr_t_d_297));
        add(new TImgModel(R.drawable.trsr_t_d_302));
        add(new TImgModel(R.drawable.trsr_t_d_303));
        add(new TImgModel(R.drawable.trsr_t_d_304));
        add(new TImgModel(R.drawable.trsr_t_d_305));
        add(new TImgModel(R.drawable.trsr_t_d_307));
        add(new TImgModel(R.drawable.trsr_t_d_308));
        add(new TImgModel(R.drawable.trsr_t_d_309));
        add(new TImgModel(R.drawable.trsr_t_d_310));
        add(new TImgModel(R.drawable.trsr_t_d_312));
        add(new TImgModel(R.drawable.trsr_t_d_313));
        add(new TImgModel(R.drawable.trsr_t_d_314));
        add(new TImgModel(R.drawable.trsr_t_d_315));
        add(new TImgModel(R.drawable.trsr_t_d_317));
        add(new TImgModel(R.drawable.trsr_t_d_318));
        add(new TImgModel(R.drawable.trsr_t_d_319));
        add(new TImgModel(R.drawable.trsr_t_d_320));
        add(new TImgModel(R.drawable.trsr_t_d_321));
        add(new TImgModel(R.drawable.trsr_t_d_322));
        add(new TImgModel(R.drawable.trsr_t_d_323));
        add(new TImgModel(R.drawable.trsr_t_d_324));
        add(new TImgModel(R.drawable.trsr_t_d_325));
        add(new TImgModel(R.drawable.trsr_t_d_326));
        add(new TImgModel(R.drawable.trsr_t_d_330));
        add(new TImgModel(R.drawable.trsr_t_d_336));
        add(new TImgModel(R.drawable.trsr_t_d_337));
        add(new TImgModel(R.drawable.trsr_t_d_338));
        add(new TImgModel(R.drawable.trsr_t_d_339));
        add(new TImgModel(R.drawable.trsr_t_d_340));
        add(new TImgModel(R.drawable.trsr_t_d_341));
        add(new TImgModel(R.drawable.trsr_t_d_342));
        add(new TImgModel(R.drawable.trsr_t_d_343));
        add(new TImgModel(R.drawable.trsr_t_d_344));
        add(new TImgModel(R.drawable.trsr_t_d_345));
        add(new TImgModel(R.drawable.trsr_t_d_348));
        add(new TImgModel(R.drawable.trsr_t_d_349));
        add(new TImgModel(R.drawable.trsr_t_d_350));
        add(new TImgModel(R.drawable.trsr_t_d_351));
        add(new TImgModel(R.drawable.trsr_t_d_352));
        add(new TImgModel(R.drawable.trsr_t_d_353));
        add(new TImgModel(R.drawable.trsr_t_d_354));
        add(new TImgModel(R.drawable.trsr_t_d_357));
        add(new TImgModel(R.drawable.trsr_t_d_359));
        add(new TImgModel(R.drawable.trsr_t_d_360));
        add(new TImgModel(R.drawable.trsr_t_d_361));
        add(new TImgModel(R.drawable.trsr_t_d_362));
        add(new TImgModel(R.drawable.trsr_t_d_363));
        add(new TImgModel(R.drawable.trsr_t_d_364));
        add(new TImgModel(R.drawable.trsr_t_d_367));
        add(new TImgModel(R.drawable.trsr_t_d_368));
        add(new TImgModel(R.drawable.trsr_t_d_369));
        add(new TImgModel(R.drawable.trsr_t_d_371));
        add(new TImgModel(R.drawable.trsr_t_d_372));
        add(new TImgModel(R.drawable.trsr_t_d_379));
        add(new TImgModel(R.drawable.trsr_t_d_381));
        add(new TImgModel(R.drawable.trsr_t_d_383));
        add(new TImgModel(R.drawable.trsr_t_d_384));
        add(new TImgModel(R.drawable.trsr_t_d_385));
        add(new TImgModel(R.drawable.trsr_t_d_386));
        add(new TImgModel(R.drawable.trsr_t_d_387));
        add(new TImgModel(R.drawable.trsr_t_d_398));
        add(new TImgModel(R.drawable.trsr_t_d_411));
        add(new TImgModel(R.drawable.trsr_t_d_412));
        add(new TImgModel(R.drawable.trsr_t_d_413));
        add(new TImgModel(R.drawable.trsr_t_d_414));
        add(new TImgModel(R.drawable.trsr_t_d_415));
        add(new TImgModel(R.drawable.trsr_t_d_416));
        add(new TImgModel(R.drawable.trsr_t_d_417));
        add(new TImgModel(R.drawable.trsr_t_d_418));
        add(new TImgModel(R.drawable.trsr_t_d_423));
        add(new TImgModel(R.drawable.trsr_t_d_424));
        add(new TImgModel(R.drawable.trsr_t_d_425));
        add(new TImgModel(R.drawable.trsr_t_d_426));
        add(new TImgModel(R.drawable.trsr_t_d_427));
        add(new TImgModel(R.drawable.trsr_t_d_428));
        add(new TImgModel(R.drawable.trsr_t_d_431));
        add(new TImgModel(R.drawable.trsr_t_d_432));
        add(new TImgModel(R.drawable.trsr_t_d_439));
        add(new TImgModel(R.drawable.trsr_t_d_440));
        add(new TImgModel(R.drawable.trsr_t_d_447));
        add(new TImgModel(R.drawable.trsr_t_d_448));
        add(new TImgModel(R.drawable.trsr_t_d_449));
        add(new TImgModel(R.drawable.trsr_t_d_450));
        add(new TImgModel(R.drawable.trsr_t_d_455));
        add(new TImgModel(R.drawable.trsr_t_d_465));
        add(new TImgModel(R.drawable.trsr_t_d_466));
        add(new TImgModel(R.drawable.trsr_t_d_467));
        add(new TImgModel(R.drawable.trsr_t_d_468));
        add(new TImgModel(R.drawable.trsr_t_d_473));
        add(new TImgModel(R.drawable.trsr_t_d_474));
        add(new TImgModel(R.drawable.trsr_t_d_475));
        add(new TImgModel(R.drawable.trsr_t_d_476));
        add(new TImgModel(R.drawable.trsr_t_d_477));
        add(new TImgModel(R.drawable.trsr_t_d_478));
        add(new TImgModel(R.drawable.trsr_t_d_479));
        add(new TImgModel(R.drawable.trsr_t_d_480));
        add(new TImgModel(R.drawable.trsr_t_d_481));
        add(new TImgModel(R.drawable.trsr_t_d_482));
        add(new TImgModel(R.drawable.trsr_t_d_483));
        add(new TImgModel(R.drawable.trsr_t_d_484));
        add(new TImgModel(R.drawable.trsr_t_d_485));
        add(new TImgModel(R.drawable.trsr_t_d_486));
        add(new TImgModel(R.drawable.trsr_t_d_489));
        add(new TImgModel(R.drawable.trsr_t_d_490));
        add(new TImgModel(R.drawable.trsr_t_d_492));
        add(new TImgModel(R.drawable.trsr_t_d_493));
        add(new TImgModel(R.drawable.trsr_t_d_494));
        add(new TImgModel(R.drawable.trsr_t_d_495));
        add(new TImgModel(R.drawable.trsr_t_d_496));
        add(new TImgModel(R.drawable.trsr_t_d_497));
        add(new TImgModel(R.drawable.trsr_t_d_498));
        add(new TImgModel(R.drawable.trsr_t_d_499));
        add(new TImgModel(R.drawable.trsr_t_d_500));
        add(new TImgModel(R.drawable.trsr_t_d_501));
        add(new TImgModel(R.drawable.trsr_t_d_502));
        add(new TImgModel(R.drawable.trsr_t_d_503));
        add(new TImgModel(R.drawable.trsr_t_d_507));
        add(new TImgModel(R.drawable.trsr_t_d_511));
        add(new TImgModel(R.drawable.trsr_t_d_512));
        add(new TImgModel(R.drawable.trsr_t_d_514));
        add(new TImgModel(R.drawable.trsr_t_d_523));
        add(new TImgModel(R.drawable.trsr_t_d_532));
        add(new TImgModel(R.drawable.trsr_t_d_533));
        add(new TImgModel(R.drawable.trsr_t_d_534));
        add(new TImgModel(R.drawable.trsr_t_d_535));
        add(new TImgModel(R.drawable.trsr_t_d_536));
        add(new TImgModel(R.drawable.trsr_t_d_540));
        add(new TImgModel(R.drawable.trsr_t_d_541));
        add(new TImgModel(R.drawable.trsr_t_d_544));
        add(new TImgModel(R.drawable.trsr_t_d_558));
        add(new TImgModel(R.drawable.trsr_t_d_563));
        add(new TImgModel(R.drawable.trsr_t_d_567));
        add(new TImgModel(R.drawable.trsr_t_d_568));
        add(new TImgModel(R.drawable.trsr_t_d_590));
        add(new TImgModel(R.drawable.trsr_t_d_593));
        add(new TImgModel(R.drawable.trsr_t_d_594));
        add(new TImgModel(R.drawable.trsr_t_d_595));
        add(new TImgModel(R.drawable.trsr_t_d_602));
        add(new TImgModel(R.drawable.trsr_t_d_603));
        add(new TImgModel(R.drawable.trsr_t_d_606));
        add(new TImgModel(R.drawable.trsr_t_d_607));
        add(new TImgModel(R.drawable.trsr_t_d_608));
        add(new TImgModel(R.drawable.trsr_t_d_609));
        add(new TImgModel(R.drawable.trsr_t_d_611));
        add(new TImgModel(R.drawable.trsr_t_d_616));
        add(new TImgModel(R.drawable.trsr_t_d_617));
        add(new TImgModel(R.drawable.trsr_t_d_642));
        add(new TImgModel(R.drawable.trsr_t_d_650));
        add(new TImgModel(R.drawable.trsr_t_d_651));
        add(new TImgModel(R.drawable.trsr_t_d_652));
        add(new TImgModel(R.drawable.trsr_t_d_653));
        add(new TImgModel(R.drawable.trsr_t_d_654));
        add(new TImgModel(R.drawable.trsr_t_d_657));
        add(new TImgModel(R.drawable.trsr_t_d_658));
        add(new TImgModel(R.drawable.trsr_t_d_661));
        add(new TImgModel(R.drawable.trsr_t_d_662));
        add(new TImgModel(R.drawable.trsr_t_d_664));
        add(new TImgModel(R.drawable.trsr_t_d_669));
        add(new TImgModel(R.drawable.trsr_t_d_676));
        add(new TImgModel(R.drawable.trsr_t_d_678));
        add(new TImgModel(R.drawable.trsr_t_d_679));
        add(new TImgModel(R.drawable.trsr_t_d_680));
        add(new TImgModel(R.drawable.trsr_t_d_681));
        add(new TImgModel(R.drawable.trsr_t_d_706));
        add(new TImgModel(R.drawable.trsr_t_d_707));
    }};
    public static List<TImgModel> tSongpa = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_g_136));
        add(new TImgModel(R.drawable.trsr_t_g_137));
    }};
    public static List<TImgModel> tSungbuk = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_h_013));
        add(new TImgModel(R.drawable.trsr_t_h_022));
        add(new TImgModel(R.drawable.trsr_t_h_023));
        add(new TImgModel(R.drawable.trsr_t_h_024));
        add(new TImgModel(R.drawable.trsr_t_h_025));
        add(new TImgModel(R.drawable.trsr_t_h_026));
        add(new TImgModel(R.drawable.trsr_t_h_041));
        add(new TImgModel(R.drawable.trsr_t_h_042));
        add(new TImgModel(R.drawable.trsr_t_h_061));
        add(new TImgModel(R.drawable.trsr_t_h_112));
        add(new TImgModel(R.drawable.trsr_t_h_113));
        add(new TImgModel(R.drawable.trsr_t_h_120));
        add(new TImgModel(R.drawable.trsr_t_h_163));
        add(new TImgModel(R.drawable.trsr_t_h_167));
        add(new TImgModel(R.drawable.trsr_t_h_168));
        add(new TImgModel(R.drawable.trsr_t_h_171));
        add(new TImgModel(R.drawable.trsr_t_h_190));
        add(new TImgModel(R.drawable.trsr_t_h_260));
        add(new TImgModel(R.drawable.trsr_t_h_265));
        add(new TImgModel(R.drawable.trsr_t_h_528));
        add(new TImgModel(R.drawable.trsr_t_h_554));
        add(new TImgModel(R.drawable.trsr_t_h_555));
        add(new TImgModel(R.drawable.trsr_t_h_581));
        add(new TImgModel(R.drawable.trsr_t_h_598));
        add(new TImgModel(R.drawable.trsr_t_h_628));
        add(new TImgModel(R.drawable.trsr_t_h_637));
        add(new TImgModel(R.drawable.trsr_t_h_643));
        add(new TImgModel(R.drawable.trsr_t_h_663));
        add(new TImgModel(R.drawable.trsr_t_h_682));
        add(new TImgModel(R.drawable.trsr_t_h_683));
        add(new TImgModel(R.drawable.trsr_t_h_684));
        add(new TImgModel(R.drawable.trsr_t_h_685));
        add(new TImgModel(R.drawable.trsr_t_h_686));
        add(new TImgModel(R.drawable.trsr_t_h_687));
        add(new TImgModel(R.drawable.trsr_t_h_688));
        add(new TImgModel(R.drawable.trsr_t_h_689));
        add(new TImgModel(R.drawable.trsr_t_h_690));
        add(new TImgModel(R.drawable.trsr_t_h_691));
        add(new TImgModel(R.drawable.trsr_t_h_692));
        add(new TImgModel(R.drawable.trsr_t_h_693));
        add(new TImgModel(R.drawable.trsr_t_h_694));
        add(new TImgModel(R.drawable.trsr_t_h_697));
        add(new TImgModel(R.drawable.trsr_t_h_698));
        add(new TImgModel(R.drawable.trsr_t_h_699));
        add(new TImgModel(R.drawable.trsr_t_h_700));
        add(new TImgModel(R.drawable.trsr_t_h_701));
        add(new TImgModel(R.drawable.trsr_t_h_702));
        add(new TImgModel(R.drawable.trsr_t_h_703));
        add(new TImgModel(R.drawable.trsr_t_h_704));
        add(new TImgModel(R.drawable.trsr_t_h_705));
    }};
    public static List<TImgModel> tSeocho = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_j_073));
        add(new TImgModel(R.drawable.trsr_t_j_169));
        add(new TImgModel(R.drawable.trsr_t_j_273));
        add(new TImgModel(R.drawable.trsr_t_j_391));
        add(new TImgModel(R.drawable.trsr_t_j_461));
        add(new TImgModel(R.drawable.trsr_t_j_556));
        add(new TImgModel(R.drawable.trsr_t_j_579));
        add(new TImgModel(R.drawable.trsr_t_j_580));
        add(new TImgModel(R.drawable.trsr_t_j_582));
        add(new TImgModel(R.drawable.trsr_t_j_635));
        add(new TImgModel(R.drawable.trsr_t_j_668));
    }};
    public static List<TImgModel> tSeodaemun = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_k_012));
        add(new TImgModel(R.drawable.trsr_t_k_043));
        add(new TImgModel(R.drawable.trsr_t_k_044));
        add(new TImgModel(R.drawable.trsr_t_k_060));
        add(new TImgModel(R.drawable.trsr_t_k_079));
        add(new TImgModel(R.drawable.trsr_t_k_080));
        add(new TImgModel(R.drawable.trsr_t_k_109));
        add(new TImgModel(R.drawable.trsr_t_k_110));
        add(new TImgModel(R.drawable.trsr_t_k_127));
        add(new TImgModel(R.drawable.trsr_t_k_129));
        add(new TImgModel(R.drawable.trsr_t_k_130));
        add(new TImgModel(R.drawable.trsr_t_k_131));
        add(new TImgModel(R.drawable.trsr_t_k_133));
        add(new TImgModel(R.drawable.trsr_t_k_134));
        add(new TImgModel(R.drawable.trsr_t_k_170));
        add(new TImgModel(R.drawable.trsr_t_k_176));
        add(new TImgModel(R.drawable.trsr_t_k_185));
        add(new TImgModel(R.drawable.trsr_t_k_203));
        add(new TImgModel(R.drawable.trsr_t_k_205));
        add(new TImgModel(R.drawable.trsr_t_k_285));
        add(new TImgModel(R.drawable.trsr_t_k_286));
        add(new TImgModel(R.drawable.trsr_t_k_287));
        add(new TImgModel(R.drawable.trsr_t_k_288));
        add(new TImgModel(R.drawable.trsr_t_k_289));
        add(new TImgModel(R.drawable.trsr_t_k_290));
        add(new TImgModel(R.drawable.trsr_t_k_291));
        add(new TImgModel(R.drawable.trsr_t_k_298));
        add(new TImgModel(R.drawable.trsr_t_k_299));
        add(new TImgModel(R.drawable.trsr_t_k_300));
        add(new TImgModel(R.drawable.trsr_t_k_301));
        add(new TImgModel(R.drawable.trsr_t_k_333));
        add(new TImgModel(R.drawable.trsr_t_k_334));
        add(new TImgModel(R.drawable.trsr_t_k_419));
        add(new TImgModel(R.drawable.trsr_t_k_420));
        add(new TImgModel(R.drawable.trsr_t_k_421));
        add(new TImgModel(R.drawable.trsr_t_k_443));
        add(new TImgModel(R.drawable.trsr_t_k_444));
        add(new TImgModel(R.drawable.trsr_t_k_445));
        add(new TImgModel(R.drawable.trsr_t_k_453));
        add(new TImgModel(R.drawable.trsr_t_k_545));
        add(new TImgModel(R.drawable.trsr_t_k_546));
        add(new TImgModel(R.drawable.trsr_t_k_550));
        add(new TImgModel(R.drawable.trsr_t_k_551));
        add(new TImgModel(R.drawable.trsr_t_k_552));
        add(new TImgModel(R.drawable.trsr_t_k_559));
        add(new TImgModel(R.drawable.trsr_t_k_639));
        add(new TImgModel(R.drawable.trsr_t_k_670));
        add(new TImgModel(R.drawable.trsr_t_k_672));
    }};
    public static List<TImgModel> tMapo = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_l_182));
        add(new TImgModel(R.drawable.trsr_t_l_591));
    }};
    public static List<TImgModel> tDongjak = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_m_087));
        add(new TImgModel(R.drawable.trsr_t_m_253));
        add(new TImgModel(R.drawable.trsr_t_m_254));
        add(new TImgModel(R.drawable.trsr_t_m_282));
    }};
    public static List<TImgModel> tDongdaemun = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_n_202));
        add(new TImgModel(R.drawable.trsr_t_n_210));
        add(new TImgModel(R.drawable.trsr_t_n_213));
        add(new TImgModel(R.drawable.trsr_t_n_249));
        add(new TImgModel(R.drawable.trsr_t_n_636));
    }};
    public static List<TImgModel> tNowon = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_p_057));
        add(new TImgModel(R.drawable.trsr_t_p_058));
        add(new TImgModel(R.drawable.trsr_t_p_266));
        add(new TImgModel(R.drawable.trsr_t_p_269));
        add(new TImgModel(R.drawable.trsr_t_p_271));
        add(new TImgModel(R.drawable.trsr_t_p_446));
        add(new TImgModel(R.drawable.trsr_t_p_549));
    }};
    public static List<TImgModel> tGwangjin = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_s_070));
    }};
    public static List<TImgModel> tGwanak = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_t_191));
        add(new TImgModel(R.drawable.trsr_t_t_192));
        add(new TImgModel(R.drawable.trsr_t_t_193));
        add(new TImgModel(R.drawable.trsr_t_t_194));
        add(new TImgModel(R.drawable.trsr_t_t_195));
        add(new TImgModel(R.drawable.trsr_t_t_196));
        add(new TImgModel(R.drawable.trsr_t_t_204));
        add(new TImgModel(R.drawable.trsr_t_t_208));
        add(new TImgModel(R.drawable.trsr_t_t_211));
        add(new TImgModel(R.drawable.trsr_t_t_212));
        add(new TImgModel(R.drawable.trsr_t_t_214));
        add(new TImgModel(R.drawable.trsr_t_t_232));
        add(new TImgModel(R.drawable.trsr_t_t_233));
        add(new TImgModel(R.drawable.trsr_t_t_234));
        add(new TImgModel(R.drawable.trsr_t_t_267));
        add(new TImgModel(R.drawable.trsr_t_t_274));
        add(new TImgModel(R.drawable.trsr_t_t_275));
        add(new TImgModel(R.drawable.trsr_t_t_281));
        add(new TImgModel(R.drawable.trsr_t_t_335));
        add(new TImgModel(R.drawable.trsr_t_t_355));
        add(new TImgModel(R.drawable.trsr_t_t_356));
        add(new TImgModel(R.drawable.trsr_t_t_358));
        add(new TImgModel(R.drawable.trsr_t_t_365));
        add(new TImgModel(R.drawable.trsr_t_t_370));
        add(new TImgModel(R.drawable.trsr_t_t_373));
        add(new TImgModel(R.drawable.trsr_t_t_374));
        add(new TImgModel(R.drawable.trsr_t_t_375));
        add(new TImgModel(R.drawable.trsr_t_t_376));
        add(new TImgModel(R.drawable.trsr_t_t_377));
        add(new TImgModel(R.drawable.trsr_t_t_388));
        add(new TImgModel(R.drawable.trsr_t_t_389));
        add(new TImgModel(R.drawable.trsr_t_t_399));
        add(new TImgModel(R.drawable.trsr_t_t_400));
        add(new TImgModel(R.drawable.trsr_t_t_401));
        add(new TImgModel(R.drawable.trsr_t_t_402));
        add(new TImgModel(R.drawable.trsr_t_t_403));
        add(new TImgModel(R.drawable.trsr_t_t_404));
        add(new TImgModel(R.drawable.trsr_t_t_405));
        add(new TImgModel(R.drawable.trsr_t_t_406));
        add(new TImgModel(R.drawable.trsr_t_t_407));
        add(new TImgModel(R.drawable.trsr_t_t_408));
        add(new TImgModel(R.drawable.trsr_t_t_409));
        add(new TImgModel(R.drawable.trsr_t_t_433));
        add(new TImgModel(R.drawable.trsr_t_t_434));
        add(new TImgModel(R.drawable.trsr_t_t_435));
        add(new TImgModel(R.drawable.trsr_t_t_454));
        add(new TImgModel(R.drawable.trsr_t_t_472));
        add(new TImgModel(R.drawable.trsr_t_t_515));
        add(new TImgModel(R.drawable.trsr_t_t_516));
        add(new TImgModel(R.drawable.trsr_t_t_517));
        add(new TImgModel(R.drawable.trsr_t_t_518));
        add(new TImgModel(R.drawable.trsr_t_t_519));
        add(new TImgModel(R.drawable.trsr_t_t_520));
        add(new TImgModel(R.drawable.trsr_t_t_521));
        add(new TImgModel(R.drawable.trsr_t_t_522));
        add(new TImgModel(R.drawable.trsr_t_t_527));
        add(new TImgModel(R.drawable.trsr_t_t_547));
        add(new TImgModel(R.drawable.trsr_t_t_557));
        add(new TImgModel(R.drawable.trsr_t_t_560));
        add(new TImgModel(R.drawable.trsr_t_t_561));
        add(new TImgModel(R.drawable.trsr_t_t_562));
        add(new TImgModel(R.drawable.trsr_t_t_564));
        add(new TImgModel(R.drawable.trsr_t_t_569));
        add(new TImgModel(R.drawable.trsr_t_t_570));
        add(new TImgModel(R.drawable.trsr_t_t_571));
        add(new TImgModel(R.drawable.trsr_t_t_572));
        add(new TImgModel(R.drawable.trsr_t_t_573));
        add(new TImgModel(R.drawable.trsr_t_t_574));
        add(new TImgModel(R.drawable.trsr_t_t_575));
        add(new TImgModel(R.drawable.trsr_t_t_576));
        add(new TImgModel(R.drawable.trsr_t_t_577));
        add(new TImgModel(R.drawable.trsr_t_t_578));
        add(new TImgModel(R.drawable.trsr_t_t_644));
        add(new TImgModel(R.drawable.trsr_t_t_645));
        add(new TImgModel(R.drawable.trsr_t_t_646));
        add(new TImgModel(R.drawable.trsr_t_t_647));
        add(new TImgModel(R.drawable.trsr_t_t_648));
        add(new TImgModel(R.drawable.trsr_t_t_649));
        add(new TImgModel(R.drawable.trsr_t_t_666));
        add(new TImgModel(R.drawable.trsr_t_t_673));
        add(new TImgModel(R.drawable.trsr_t_t_708));
    }};
    public static List<TImgModel> tGangseo = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_u_390));
        add(new TImgModel(R.drawable.trsr_t_u_451));
    }};
    public static List<TImgModel> tGangbuk = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_v_004));
        add(new TImgModel(R.drawable.trsr_t_v_641));
    }};
    public static List<TImgModel> tGangnam = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_x_604));
        add(new TImgModel(R.drawable.trsr_t_x_638));
        add(new TImgModel(R.drawable.trsr_t_x_677));
    }};
    public static List<TImgModel> tJongno = new ArrayList<TImgModel>() {{
        add(new TImgModel(R.drawable.trsr_t_y_001));
        add(new TImgModel(R.drawable.trsr_t_y_003));
        add(new TImgModel(R.drawable.trsr_t_y_005));
        add(new TImgModel(R.drawable.trsr_t_y_006));
        add(new TImgModel(R.drawable.trsr_t_y_008));
        add(new TImgModel(R.drawable.trsr_t_y_010));
        add(new TImgModel(R.drawable.trsr_t_y_011));
        add(new TImgModel(R.drawable.trsr_t_y_015));
        add(new TImgModel(R.drawable.trsr_t_y_017));
        add(new TImgModel(R.drawable.trsr_t_y_020));
        add(new TImgModel(R.drawable.trsr_t_y_027));
        add(new TImgModel(R.drawable.trsr_t_y_052));
        add(new TImgModel(R.drawable.trsr_t_y_053));
        add(new TImgModel(R.drawable.trsr_t_y_054));
        add(new TImgModel(R.drawable.trsr_t_y_055));
        add(new TImgModel(R.drawable.trsr_t_y_056));
        add(new TImgModel(R.drawable.trsr_t_y_062));
        add(new TImgModel(R.drawable.trsr_t_y_118));
        add(new TImgModel(R.drawable.trsr_t_y_235));
        add(new TImgModel(R.drawable.trsr_t_y_236));
        add(new TImgModel(R.drawable.trsr_t_y_237));
        add(new TImgModel(R.drawable.trsr_t_y_238));
        add(new TImgModel(R.drawable.trsr_t_y_239));
        add(new TImgModel(R.drawable.trsr_t_y_240));
        add(new TImgModel(R.drawable.trsr_t_y_241));
        add(new TImgModel(R.drawable.trsr_t_y_242));
        add(new TImgModel(R.drawable.trsr_t_y_243));
        add(new TImgModel(R.drawable.trsr_t_y_244));
        add(new TImgModel(R.drawable.trsr_t_y_247));
        add(new TImgModel(R.drawable.trsr_t_y_248));
        add(new TImgModel(R.drawable.trsr_t_y_250));
        add(new TImgModel(R.drawable.trsr_t_y_251));
        add(new TImgModel(R.drawable.trsr_t_y_252));
        add(new TImgModel(R.drawable.trsr_t_y_255));
        add(new TImgModel(R.drawable.trsr_t_y_256));
        add(new TImgModel(R.drawable.trsr_t_y_257));
        add(new TImgModel(R.drawable.trsr_t_y_258));
        add(new TImgModel(R.drawable.trsr_t_y_261));
        add(new TImgModel(R.drawable.trsr_t_y_263));
        add(new TImgModel(R.drawable.trsr_t_y_268));
        add(new TImgModel(R.drawable.trsr_t_y_270));
        add(new TImgModel(R.drawable.trsr_t_y_272));
        add(new TImgModel(R.drawable.trsr_t_y_306));
        add(new TImgModel(R.drawable.trsr_t_y_327));
        add(new TImgModel(R.drawable.trsr_t_y_328));
        add(new TImgModel(R.drawable.trsr_t_y_329));
        add(new TImgModel(R.drawable.trsr_t_y_331));
        add(new TImgModel(R.drawable.trsr_t_y_378));
        add(new TImgModel(R.drawable.trsr_t_y_382));
        add(new TImgModel(R.drawable.trsr_t_y_392));
        add(new TImgModel(R.drawable.trsr_t_y_393));
        add(new TImgModel(R.drawable.trsr_t_y_394));
        add(new TImgModel(R.drawable.trsr_t_y_395));
        add(new TImgModel(R.drawable.trsr_t_y_396));
        add(new TImgModel(R.drawable.trsr_t_y_397));
        add(new TImgModel(R.drawable.trsr_t_y_410));
        add(new TImgModel(R.drawable.trsr_t_y_436));
        add(new TImgModel(R.drawable.trsr_t_y_441));
        add(new TImgModel(R.drawable.trsr_t_y_456));
        add(new TImgModel(R.drawable.trsr_t_y_462));
        add(new TImgModel(R.drawable.trsr_t_y_463));
        add(new TImgModel(R.drawable.trsr_t_y_464));
        add(new TImgModel(R.drawable.trsr_t_y_469));
        add(new TImgModel(R.drawable.trsr_t_y_470));
        add(new TImgModel(R.drawable.trsr_t_y_471));
        add(new TImgModel(R.drawable.trsr_t_y_487));
        add(new TImgModel(R.drawable.trsr_t_y_508));
        add(new TImgModel(R.drawable.trsr_t_y_509));
        add(new TImgModel(R.drawable.trsr_t_y_510));
        add(new TImgModel(R.drawable.trsr_t_y_526));
        add(new TImgModel(R.drawable.trsr_t_y_529));
        add(new TImgModel(R.drawable.trsr_t_y_530));
        add(new TImgModel(R.drawable.trsr_t_y_531));
        add(new TImgModel(R.drawable.trsr_t_y_537));
        add(new TImgModel(R.drawable.trsr_t_y_538));
        add(new TImgModel(R.drawable.trsr_t_y_539));
        add(new TImgModel(R.drawable.trsr_t_y_542));
        add(new TImgModel(R.drawable.trsr_t_y_543));
        add(new TImgModel(R.drawable.trsr_t_y_553));
        add(new TImgModel(R.drawable.trsr_t_y_565));
        add(new TImgModel(R.drawable.trsr_t_y_583));
        add(new TImgModel(R.drawable.trsr_t_y_584));
        add(new TImgModel(R.drawable.trsr_t_y_585));
        add(new TImgModel(R.drawable.trsr_t_y_586));
        add(new TImgModel(R.drawable.trsr_t_y_587));
        add(new TImgModel(R.drawable.trsr_t_y_588));
        add(new TImgModel(R.drawable.trsr_t_y_589));
        add(new TImgModel(R.drawable.trsr_t_y_597));
        add(new TImgModel(R.drawable.trsr_t_y_599));
        add(new TImgModel(R.drawable.trsr_t_y_600));
        add(new TImgModel(R.drawable.trsr_t_y_612));
        add(new TImgModel(R.drawable.trsr_t_y_614));
        add(new TImgModel(R.drawable.trsr_t_y_618));
        add(new TImgModel(R.drawable.trsr_t_y_620));
        add(new TImgModel(R.drawable.trsr_t_y_622));
        add(new TImgModel(R.drawable.trsr_t_y_623));
        add(new TImgModel(R.drawable.trsr_t_y_624));
        add(new TImgModel(R.drawable.trsr_t_y_625));
        add(new TImgModel(R.drawable.trsr_t_y_626));
        add(new TImgModel(R.drawable.trsr_t_y_627));
        add(new TImgModel(R.drawable.trsr_t_y_629));
        add(new TImgModel(R.drawable.trsr_t_y_630));
        add(new TImgModel(R.drawable.trsr_t_y_631));
        add(new TImgModel(R.drawable.trsr_t_y_632));
        add(new TImgModel(R.drawable.trsr_t_y_633));
        add(new TImgModel(R.drawable.trsr_t_y_634));
        add(new TImgModel(R.drawable.trsr_t_y_640));
        add(new TImgModel(R.drawable.trsr_t_y_656));
        add(new TImgModel(R.drawable.trsr_t_y_667));
        add(new TImgModel(R.drawable.trsr_t_y_671));
        add(new TImgModel(R.drawable.trsr_t_y_674));

    }};
}
